sudo: false
language: python
cache: pip

python:
- '2.7'
- '3.4'

env:
  ## TODO: Remove this for your own projects. This is needed for the project template only.
- DJANGO_SETTINGS_MODULE=project_name.settings.unittest

before_install:
  ## TODO: remove this for your own projects. This removes the {{ project_name }} for the Django settings
- sed -i -e 's/{{ project_name }}/project_name/g' src/project_name/settings/*.py src/*.py src/frontend/views.py
- sed -i -e 's/{{ secret_key|safe }}/c6!x_#)=rim8n1j90f#al%m9i)zb2zu@i)846ps_&%-5@6o=q6/g' src/project_name/settings/defaults.py

install:
- pip install -U pip wheel setuptools
- pip install -r src/requirements/unittest.txt

before_script: cd src
script:
- ./manage.py check --fail-level=WARNING
- coverage run --source=project_name,frontend ./manage.py check --fail-level=WARNING --deploy --settings=project_name.settings.docker
- coverage run --source=project_name,frontend --append pytest

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    ## TODO: Replace this for your own projects
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
#  slack:
#    secure: ....
#    on_success: never
#    on_failure: always
