sudo: false
language: python
cache: pip
python:
- '2.7'
- '3.4'
install:
- travis_retry pip install -r requirements.txt
script:
- coverage run --source=project_name,apps runtests.py --settings=project_name.settings.env.unittest
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    ## TODO: Replace this for your own projects
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
#  slack:
#    secure: ....
#    on_success: never
#    on_failure: always
