sudo: false
language: python
cache: pip

python:
- '2.7'
- '3.4'

env:
  ## TODO: Remove this for your own projects. This is needed for the project template only.
- DJANGO_SETTINGS_MODULE=project_name.settings.env.unittest

install:
- pip install -U pip wheel setuptools
- pip install $PACKAGES -r requirements.txt
  ## TODO: remove this for your own projects. This removes the {{ project_name }} for the Django settings
- sed -i '' -e 's/{{ project_name }}/project_name/g' project_name/settings/defaults.py project_name/settings/project.py

script:
- python manage.py check
- coverage run --source=project_name,apps --omit='*/migrations/*' runtests.py

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    ## TODO: Replace this for your own projects
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
#  slack:
#    secure: ....
#    on_success: never
#    on_failure: always
