sudo: required
language: python
cache: pip
services:
- docker

python:
- '2.7'
- '3.4'

## TODO: remove this for your own projects.
install:
- pip install -U pip wheel setuptools 'Django<2.0'
- mkdir ../build; django-admin.py startproject -e py,rst,example,gitignore,ini,min -n Dockerfile --template=. myproject ../build
before_script:
- export DJANGO_SETTINGS_MODULE=myproject.settings.unittest
- cd ../build/src

script:
  # Fast local testing against Travis python
- pip install -r requirements/unittest.txt
- py.test --cov
- coverage run --append --source=myproject,frontend ./manage.py check --fail-level=WARNING --deploy --settings=myproject.settings.docker
- ./manage.py check --fail-level=WARNING
  # Build image
- |
  docker build -t myproject:latest-min -f ../Dockerfile.min .. &&
  docker run --net=host --name=myproject --detach --rm -p 8080:8080 -e EMAIL_URL=consolemail:// myproject:latest-min &&
  sleep 2 &&
  curl -Lsv http://localhost:8080/ &&
  docker stop myproject
- docker build -t myproject:latest .. &&

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    ## TODO: Replace this for your own projects
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
#  slack:
#    secure: ....
#    on_success: never
#    on_failure: always
